// This file is automatically generated. Do not modify it manually.

package main

import (
	"strings"

	"github.com/mattermost/mattermost-server/v5/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "set-default-theme",
  "name": "Set Default Theme",
  "description": "Apply a custom theme to all users when they create their account.",
  "version": "1.0.0",
  "min_server_version": "5.26.0",
  "server": {
    "executables": {
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "windows-amd64": "server/dist/plugin-windows-amd64.exe"
    },
    "executable": ""
  },
  "settings_schema": {
    "header": "",
    "footer": "",
    "settings": [
      {
        "key": "CustomTheme",
        "display_name": "Default Theme",
        "type": "longtext",
        "help_text": "Custom Theme JSON",
        "placeholder": "",
        "default": ""
      }
    ]
  }
}
`

func init() {
	manifest = model.ManifestFromJson(strings.NewReader(manifestStr))
}
